In [31]:
# ==========================================
# Notebook 04
# Item Embedding Generator
# ==========================================

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

In [32]:
profiles_df = pd.read_csv("../data/item_profiles.csv")

profiles_df.head()

,item_id,title,category,tags,content_profile
0,1,The Early Days of Stripe,Startup,startup fintech founders entrepreneurship vent...,Title: The Early Days of Stripe Category: Star...
1,2,Building SpaceX,Startup,startup fintech founders entrepreneurship vent...,Title: Building SpaceX Category: Startup Tags:...
2,3,AI for Healthcare,Artificial Intelligence,ai machine-learning llm deep-learning transfor...,Title: AI for Healthcare Category: Artificial ...
3,4,The Psychology of Habits,Wellness,habits productivity self-improvement,Title: The Psychology of Habits Category: Well...
4,5,Cloud Computing Fundamentals,Technology,cloud computing distributed-systems scalability,Title: Cloud Computing Fundamentals Category: ...


In [33]:
print("Total Profiles:", len(profiles_df))

print()

profiles_df.columns

Total Profiles: 10



Index(['item_id', 'title', 'category', 'tags', 'content_profile'], dtype='object')

In [34]:
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

In [35]:
embedding_model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [36]:
documents = profiles_df["content_profile"].tolist()

In [37]:
len(documents)

10

In [38]:
documents[0]

"Title: The Early Days of Stripe Category: Startup Tags: startup fintech founders entrepreneurship venture-capital Description: \n        Story of how Stripe scaled into\n        one of the world's largest\n        fintech companies.\n        "

In [39]:
item_embeddings = embedding_model.encode(documents, show_progress_bar=True)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [40]:
item_embeddings.shape

(10, 384)

In [41]:
item_embeddings[0]

array([-2.13364158e-02,  1.58938149e-03, -5.13304211e-02, -2.97792517e-02,
       -6.60088519e-03, -1.55283250e-02,  4.08354737e-02,  5.16616590e-02,
       -3.39248516e-02, -1.50033319e-02, -1.02398349e-02,  2.82043610e-02,
       -3.83497365e-02,  9.01229307e-02, -2.39704512e-02, -2.84749009e-02,
       -1.04348548e-02, -5.19594029e-02,  3.05004697e-02,  3.37638296e-02,
       -4.49055471e-02, -8.00923258e-02,  1.04316426e-02,  5.39698564e-02,
        6.75261766e-02,  4.06304002e-02,  7.26671470e-03,  2.56847125e-04,
       -5.50831743e-02, -1.07916445e-01, -3.29991281e-02,  7.41584674e-02,
        5.67254126e-02,  1.07447077e-02,  4.00880910e-02, -4.81372932e-03,
        1.62653793e-02, -3.01518701e-02, -3.61125846e-03, -4.47111130e-02,
        1.03005104e-01, -5.82102090e-02, -3.43533196e-02,  1.58608425e-02,
        5.19482791e-02, -7.05559552e-02, -1.17440745e-02,  6.94275601e-03,
       -1.04182921e-02,  5.57733774e-02,  3.55312377e-02, -1.22866936e-01,
        5.83510436e-02, -

In [42]:
len(item_embeddings[0])

384

In [43]:
embedding_df = pd.DataFrame(item_embeddings)

embedding_df.head()

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.021336,0.001589,-0.051330,-0.029779,-0.006601,-0.015528,0.040835,0.051662,-0.033925,-0.015003,...,0.011316,-0.018862,0.006963,0.038462,-0.017133,0.037925,0.120517,-0.056864,0.075505,-0.017933
1,0.027306,-0.047626,0.016753,-0.061527,-0.021008,-0.032888,0.060912,0.015195,-0.045884,-0.027095,...,0.018612,0.039884,-0.038688,0.084618,0.010697,-0.029886,0.074290,-0.029545,0.028936,0.027559
2,-0.078346,-0.004525,0.003929,-0.066090,0.005532,-0.042065,-0.010277,0.042649,-0.051656,-0.066911,...,0.051748,0.059906,0.077221,-0.086342,0.003354,0.104092,0.037527,0.044017,-0.044965,-0.021307
3,0.068490,0.005979,-0.040110,0.064891,-0.051967,-0.014224,0.062593,0.006003,-0.071438,-0.021358,...,-0.024052,0.011927,0.051691,0.012610,-0.052049,-0.050758,0.143781,0.028030,-0.015431,-0.014873
4,0.018681,0.029413,-0.065553,-0.074235,0.032086,-0.043718,0.017604,0.014345,-0.037435,0.057680,...,0.035586,-0.028311,0.017458,-0.045064,0.122665,0.085353,0.058242,0.034240,0.009545,0.059948


In [44]:
embedding_df.insert(0, "item_id", profiles_df["item_id"])

In [45]:
embedding_df.head()

,item_id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
0,1,-0.021336,0.001589,-0.051330,-0.029779,-0.006601,-0.015528,0.040835,0.051662,-0.033925,...,0.011316,-0.018862,0.006963,0.038462,-0.017133,0.037925,0.120517,-0.056864,0.075505,-0.017933
1,2,0.027306,-0.047626,0.016753,-0.061527,-0.021008,-0.032888,0.060912,0.015195,-0.045884,...,0.018612,0.039884,-0.038688,0.084618,0.010697,-0.029886,0.074290,-0.029545,0.028936,0.027559
2,3,-0.078346,-0.004525,0.003929,-0.066090,0.005532,-0.042065,-0.010277,0.042649,-0.051656,...,0.051748,0.059906,0.077221,-0.086342,0.003354,0.104092,0.037527,0.044017,-0.044965,-0.021307
3,4,0.068490,0.005979,-0.040110,0.064891,-0.051967,-0.014224,0.062593,0.006003,-0.071438,...,-0.024052,0.011927,0.051691,0.012610,-0.052049,-0.050758,0.143781,0.028030,-0.015431,-0.014873
4,5,0.018681,0.029413,-0.065553,-0.074235,0.032086,-0.043718,0.017604,0.014345,-0.037435,...,0.035586,-0.028311,0.017458,-0.045064,0.122665,0.085353,0.058242,0.034240,0.009545,0.059948


In [46]:
embedding_df.isnull().sum().sum()

0

In [47]:
embedding_df.describe()

,item_id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,5.50000,-0.009853,-0.006273,-0.025165,-0.017841,0.008254,-0.042905,0.011319,0.017810,-0.057137,...,0.022463,0.025335,0.020524,-0.008694,0.014390,0.013380,0.091157,0.016215,0.010402,0.005241
std,3.02765,0.050377,0.029727,0.039911,0.055487,0.037936,0.041377,0.035658,0.022623,0.026783,...,0.037266,0.030859,0.032015,0.056779,0.051204,0.058338,0.038049,0.042383,0.037232,0.025935
min,1.00000,-0.078346,-0.053915,-0.072981,-0.074235,-0.051967,-0.151249,-0.034299,-0.007948,-0.122550,...,-0.051090,-0.028311,-0.038688,-0.086342,-0.052049,-0.050758,0.037527,-0.056864,-0.044965,-0.021307
25%,3.25000,-0.051291,-0.028740,-0.048525,-0.060565,-0.017406,-0.043526,-0.021528,0.000674,-0.062738,...,0.013140,0.014321,0.006963,-0.044491,-0.015500,-0.034015,0.061118,-0.013285,-0.019299,-0.014011
50%,5.50000,-0.006548,0.002412,-0.035769,-0.033599,0.004259,-0.037477,0.014427,0.010445,-0.053591,...,0.027315,0.028314,0.019818,-0.018626,-0.002736,0.004763,0.083475,0.026361,0.011094,-0.002458
75%,7.75000,0.025149,0.011586,-0.003895,0.029078,0.038212,-0.017362,0.035028,0.035786,-0.039547,...,0.047708,0.042040,0.038243,0.031999,0.045684,0.051689,0.120011,0.041573,0.028258,0.022370
max,10.00000,0.068490,0.029413,0.056544,0.064891,0.064067,-0.005828,0.062593,0.052042,-0.028310,...,0.074591,0.067917,0.077221,0.084618,0.122665,0.104092,0.143781,0.081593,0.075505,0.059948


In [48]:
item_a = item_embeddings[0]

item_b = item_embeddings[1]

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity = cosine_similarity(item_a.reshape(1, -1), item_b.reshape(1, -1))[0][0]

similarity

0.6049122

In [51]:
similarity_matrix = cosine_similarity(item_embeddings)

similarity_matrix

array([[1.0000002 , 0.60491216, 0.09593558, 0.20255241, 0.2823203 ,
        0.21441258, 0.30493483, 0.62655663, 0.23472585, 0.10024057],
       [0.60491216, 1.0000002 , 0.1717555 , 0.20117478, 0.25644535,
        0.30296105, 0.35528207, 0.79167366, 0.33665824, 0.20764989],
       [0.09593558, 0.1717555 , 1.        , 0.1501966 , 0.26319483,
        0.29961205, 0.48962337, 0.18523768, 0.34414434, 0.6893631 ],
       [0.20255241, 0.20117478, 0.1501966 , 1.0000001 , 0.16988723,
        0.16885036, 0.21340138, 0.29436833, 0.58422685, 0.14165233],
       [0.2823203 , 0.25644535, 0.26319483, 0.16988723, 0.9999998 ,
        0.40530014, 0.29446724, 0.27513355, 0.26107383, 0.253823  ],
       [0.21441258, 0.30296105, 0.29961205, 0.16885036, 0.40530014,
        1.0000001 , 0.38773024, 0.27713224, 0.35022694, 0.35668528],
       [0.30493483, 0.35528207, 0.48962337, 0.21340138, 0.29446724,
        0.38773024, 1.        , 0.44833386, 0.3759947 , 0.46243042],
       [0.62655663, 0.79167366, 0.1852376

In [52]:
similarity_matrix.shape

(10, 10)

In [53]:
similarity_df = pd.DataFrame(
    similarity_matrix, index=profiles_df["title"], columns=profiles_df["title"]
)

similarity_df

title,The Early Days of Stripe,Building SpaceX,AI for Healthcare,The Psychology of Habits,Cloud Computing Fundamentals,Modern Data Engineering,Machine Learning in Finance,Startup Fundraising Guide,Nutrition Science,Large Language Models
title,,,,,,,,,,
The Early Days of Stripe,1.000000,0.604912,0.095936,0.202552,0.282320,0.214413,0.304935,0.626557,0.234726,0.100241
Building SpaceX,0.604912,1.000000,0.171755,0.201175,0.256445,0.302961,0.355282,0.791674,0.336658,0.207650
AI for Healthcare,0.095936,0.171755,1.000000,0.150197,0.263195,0.299612,0.489623,0.185238,0.344144,0.689363
The Psychology of Habits,0.202552,0.201175,0.150197,1.000000,0.169887,0.168850,0.213401,0.294368,0.584227,0.141652
Cloud Computing Fundamentals,0.282320,0.256445,0.263195,0.169887,1.000000,0.405300,0.294467,0.275134,0.261074,0.253823
Modern Data Engineering,0.214413,0.302961,0.299612,0.168850,0.405300,1.000000,0.387730,0.277132,0.350227,0.356685
Machine Learning in Finance,0.304935,0.355282,0.489623,0.213401,0.294467,0.387730,1.000000,0.448334,0.375995,0.462430
Startup Fundraising Guide,0.626557,0.791674,0.185238,0.294368,0.275134,0.277132,0.448334,1.000000,0.482051,0.203932
Nutrition Science,0.234726,0.336658,0.344144,0.584227,0.261074,0.350227,0.375995,0.482051,1.000000,0.240134


In [54]:
target_index = 0

scores = similarity_matrix[target_index]

scores

array([1.0000002 , 0.60491216, 0.09593558, 0.20255241, 0.2823203 ,
       0.21441258, 0.30493483, 0.62655663, 0.23472585, 0.10024057],
      dtype=float32)

In [55]:
ranked_idx = np.argsort(scores)[::-1]

In [56]:
for idx in ranked_idx[:5]:

    print()

    print(profiles_df.iloc[idx]["title"])

    print(round(scores[idx], 4))


The Early Days of Stripe
1.0

Startup Fundraising Guide
0.6266

Building SpaceX
0.6049

Machine Learning in Finance
0.3049

Cloud Computing Fundamentals
0.2823


In [57]:
embedding_metadata = profiles_df[["item_id", "title", "category"]]

In [58]:
embedding_metadata.head()

,item_id,title,category
0,1,The Early Days of Stripe,Startup
1,2,Building SpaceX,Startup
2,3,AI for Healthcare,Artificial Intelligence
3,4,The Psychology of Habits,Wellness
4,5,Cloud Computing Fundamentals,Technology


In [59]:
embedding_metadata.head()

,item_id,title,category
0,1,The Early Days of Stripe,Startup
1,2,Building SpaceX,Startup
2,3,AI for Healthcare,Artificial Intelligence
3,4,The Psychology of Habits,Wellness
4,5,Cloud Computing Fundamentals,Technology


In [60]:
np.save("../data/item_embeddings.npy", item_embeddings)

In [61]:
embedding_df.to_csv("../data/item_embeddings.csv", index=False)

In [62]:
embedding_metadata.to_csv("../data/item_embedding_metadata.csv", index=False)

In [63]:
loaded_embeddings = np.load("../data/item_embeddings.npy")

loaded_embeddings.shape

(10, 384)